import type { BlogPostMeta } from "@/components/blog-post-layout";

export const posts: BlogPostMeta[] = [
  {
    slug: "what-is-seo-in-digital-marketing",
    title: "What is SEO in digital marketing? The 2026 business owner's guide",
    description: "SEO is the part of digital marketing that compounds instead of resetting every month. This guide explains how SEO works, what actually moves rankings, how AI search changes the job, and what a business should expect in the first 90 days.",
    publishedAt: "2026-05-30",
    readTime: "10 min",
    category: "SEO",
  },
  {
    slug: "seo-content-writing-guide",
    title: "SEO content writing: how to write pages that rank and convert",
    description: "SEO content writing is not keyword stuffing or generic blog production. It is the process of answering a buyer's search better than every competing page, then connecting that answer to a conversion path. Here is the practical framework.",
    publishedAt: "2026-05-30",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "how-to-choose-a-digital-marketing-agency",
    title: "How to choose a digital marketing agency without getting trapped",
    description: "Most agency selection advice is too soft. This guide gives business owners a due diligence process for choosing a digital marketing partner, spotting weak retainers, checking ownership terms, and demanding accountable SEO outcomes.",
    publishedAt: "2026-05-30",
    readTime: "9 min",
    category: "Agency",
  },
  {
    slug: "seo-for-real-estate-companies",
    title: "SEO for real estate companies: how to turn searches into viewings",
    description: "Real estate buyers search before they call. This guide shows developers, brokers, and agencies how to build local landing pages, property content, Google Business Profile signals, and AI-ready answers that generate qualified enquiries.",
    publishedAt: "2026-05-30",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "seo-for-healthcare-providers",
    title: "SEO for healthcare providers: how clinics earn patient trust online",
    description: "Healthcare SEO has to do more than rank. It must build trust before the appointment. This guide explains service pages, doctor credibility, local search, reviews, schema, and AI citation readiness for clinics and healthcare providers.",
    publishedAt: "2026-05-30",
    readTime: "10 min",
    category: "SEO",
  },
  {
    slug: "digital-marketing-tips-for-small-businesses",
    title: "Digital marketing tips for small businesses that cannot waste budget",
    description: "Small businesses do not need every digital marketing channel at once. They need a search-first system: a fast website, local SEO, proof, content for buyer questions, and one clear conversion path. Here is the practical order.",
    publishedAt: "2026-05-30",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "seo-vs-aeo-vs-geo",
    title: "SEO vs AEO vs GEO: what's the difference, and why all three matter",
    description: "SEO ranks you on Google. AEO gets you cited by ChatGPT and Perplexity. GEO optimises for generative AI search. This is the full breakdown of how the three disciplines differ, where they overlap, and why a business that only does SEO in 2026 is losing buyers to competitors who do all three.",
    publishedAt: "2026-05-22",
    readTime: "9 min",
    category: "AEO / GEO",
  },
  {
    slug: "how-long-does-seo-take",
    title: "How long does SEO take to work? Honest timelines for 2026",
    description: "Most SEO agencies will not give you a straight answer on timelines. Here is one. With a clean site, focused content, and scoped keywords, top 3 rankings are possible in 90 days. Competitive terms take longer. Here is the breakdown by domain age, competition level, and budget.",
    publishedAt: "2026-05-22",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "how-much-does-seo-cost",
    title: "How much does SEO cost in 2026? Every pricing model explained",
    description: "SEO pricing ranges from $300 monthly retainers to $50,000 enterprise contracts. The price has almost nothing to do with the results. Here is what each pricing model actually buys you, and how to know when you are overpaying.",
    publishedAt: "2026-05-22",
    readTime: "10 min",
    category: "Agency",
  },
  {
    slug: "how-to-choose-an-seo-agency",
    title: "How to choose an SEO agency: 12 questions to ask before you sign",
    description: "Most SEO agencies will not survive your second meeting if you ask the right questions. Here are the 12 questions that separate agencies that deliver from agencies that bill. Use these in your shortlist calls.",
    publishedAt: "2026-05-22",
    readTime: "9 min",
    category: "Agency",
  },
  {
    slug: "what-is-geo-generative-engine-optimization",
    title: "What is GEO (Generative Engine Optimization)?",
    description: "GEO is the practice of optimising content so generative AI engines pull from it when answering user questions. It overlaps with AEO but focuses specifically on the generative aspect: how AI engines compose answers from your content, not just whether they cite you.",
    publishedAt: "2026-05-22",
    readTime: "7 min",
    category: "AEO / GEO",
  },
  {
    slug: "will-ai-replace-google-search",
    title: "Will AI replace Google search? The honest answer for 2026",
    description: "AI assistants now handle queries Google used to dominate. But Google is also embedding AI directly into search. Here is what the data actually shows about the shift, what it means for your traffic, and how to adapt before your competitors do.",
    publishedAt: "2026-05-22",
    readTime: "8 min",
    category: "AEO / GEO",
  },
  {
    slug: "why-isnt-my-website-ranking-on-google",
    title: "Why isn't my website ranking on Google? 9 most common reasons",
    description: "If your business is not on the first page for the searches your buyers run, it is almost always one of these nine reasons. Most are fixable in under 30 days. Here is the diagnostic order.",
    publishedAt: "2026-05-22",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "do-i-need-a-new-website-for-seo",
    title: "Do I need a new website for SEO? When to rebuild vs optimise",
    description: "A new website is one of the fastest ways to fix bad SEO, but it is also one of the most expensive mistakes if your existing site is fundamentally fine. Here is how to tell which side you are on, and what to do about it.",
    publishedAt: "2026-05-22",
    readTime: "7 min",
    category: "Web Design",
  },
  {
    slug: "what-is-local-seo",
    title: "What is Local SEO, and does your business actually need it?",
    description: "Local SEO is the discipline of ranking in the searches buyers run when they want a business near them. If your customers ever search 'near me' or include a city in their queries, you need it. Here is what it actually involves.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "keyword-research-for-small-business",
    title: "Keyword research for small businesses: a practical 30-minute method",
    description: "Most keyword research advice is built for agencies running enterprise SEO. Small businesses do not need that. Here is a 30-minute method that finds the keywords worth targeting, without paid tools or fluff.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "what-are-backlinks-and-how-to-get-them",
    title: "What are backlinks, and how do you actually get them in 2026?",
    description: "Backlinks remain the biggest off-page Google ranking factor. Most agencies are bad at getting them. Here is how good backlinks are built, which tactics work, which destroy domains, and what to do as a small business with no PR budget.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "schema-markup-for-beginners",
    title: "Schema markup for beginners: what it is, why it matters, with examples",
    description: "Schema markup is the JSON-LD code that tells Google and AI engines what your business actually is. Most sites have none of it. Here is what schema does, which types matter, and copy-paste examples for the schemas your site probably needs.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "google-business-profile-setup-guide",
    title: "Google Business Profile: the complete 2026 setup guide",
    description: "Your Google Business Profile is where most local searches end. For some businesses it drives more leads than the entire website. Here is how to set it up properly, fields most people skip, and what to do about it weekly.",
    publishedAt: "2026-05-23",
    readTime: "10 min",
    category: "SEO",
  },
  {
    slug: "how-to-optimise-for-google-ai-overviews",
    title: "How to optimise for Google AI Overviews",
    description: "Google AI Overviews now appear above traditional search results for a growing share of queries. They get clicks before organic listings do. Here is how to get pulled into the Overview, and how to recover traffic if you have already lost it.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "AEO / GEO",
  },
  {
    slug: "seo-for-new-domains-first-90-days",
    title: "SEO for new domains: what actually works in the first 90 days",
    description: "Google deliberately holds new domains in a probationary state. Trying to rank for competitive head terms on day 1 is a losing strategy. Here is what does work for new sites in the first 90 days, sequenced by week.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "eeat-explained-why-google-trusts-sites",
    title: "E-E-A-T explained: why Google trusts some sites and not yours yet",
    description: "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) is the framework Google uses to decide which sites to surface for queries that affect health, finance, legal, and other high-stakes topics. Here is what it actually requires.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "technical-seo-checklist",
    title: "Technical SEO checklist: 21 things to fix before you write a single blog post",
    description: "Technical SEO is what determines whether Google can crawl, render, and rank your site. Get this wrong and the best content strategy on Earth will fail. Here is the 21-point checklist you should run through before launching any site.",
    publishedAt: "2026-05-23",
    readTime: "10 min",
    category: "SEO",
  },
  {
    slug: "how-to-write-meta-titles-and-descriptions",
    title: "How to write meta titles and descriptions that actually get clicks",
    description: "Meta titles and descriptions are your one-shot SERP pitch to a searcher. Most sites waste them on auto-generated junk. Here is how to write titles and descriptions that get clicked, with patterns that work and patterns that do not.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "mobile-first-indexing-explained",
    title: "Mobile-first indexing explained: what Google actually crawls in 2026",
    description: "Google now indexes the mobile version of your site, not the desktop one. If your mobile experience is worse than your desktop experience, you are showing Google your worst content. Here is what mobile-first means and how to audit yours.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "internal-linking-strategy",
    title: "Internal linking strategy: how to pass authority between your pages",
    description: "Internal links tell Google which pages on your site matter most and pass authority between them. Most sites do this badly. Here is a simple strategy that works for sites of any size, with examples.",
    publishedAt: "2026-05-23",
    readTime: "8 min",
    category: "SEO",
  },
  {
    slug: "why-did-my-google-ranking-drop",
    title: "Why did my Google ranking drop? A diagnostic and recovery playbook",
    description: "Sudden ranking drops are stressful and the cause is rarely obvious. Here is the diagnostic order to identify what happened, plus recovery playbooks for the most common causes.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
  {
    slug: "seo-for-ecommerce-stores",
    title: "SEO for e-commerce stores: the 2026 playbook",
    description: "E-commerce SEO works differently from service business SEO. Product pages, category pages, faceted navigation, and structured data all require specific approaches. Here is the 2026 playbook for ranking an e-commerce store.",
    publishedAt: "2026-05-23",
    readTime: "10 min",
    category: "SEO",
  },
  {
    slug: "ai-search-optimisation-for-b2b-saas",
    title: "AI search optimisation for B2B SaaS",
    description: "B2B SaaS buyers now ask ChatGPT and Perplexity for tool recommendations before they ever open Google. Here is how SaaS companies should approach AI search optimisation, from category positioning to comparison content.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "AEO / GEO",
  },
  {
    slug: "common-seo-myths-debunked",
    title: "12 common SEO myths debunked",
    description: "SEO is a field full of half-truths and outdated advice. Here are the 12 most common myths that still circulate in 2026, what is actually true, and what to do instead.",
    publishedAt: "2026-05-23",
    readTime: "9 min",
    category: "SEO",
  },
];

export function getPost(slug: string): BlogPostMeta | undefined {
  return posts.find((p) => p.slug === slug);
}
